
/*
	File generated by NetTiers templates [www.NetTiers.com]
	Important: Do not modify this file. Edit the file Vw_CustomerList.cs instead.
*/

#region Using Directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Collections.Generic;
using System.Security.Permissions;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.Security;
using System.Data;

using CONFDB.Entities;
using CONFDB.Entities.Validation;
using Entities = CONFDB.Entities;
using CONFDB.Data;
using CONFDB.Data.Bases;


using Microsoft.Practices.EnterpriseLibrary.Logging;

#endregion 

namespace CONFDB.Services
{		
	
	///<summary>
	/// An object representation of the 'vw_CustomerList' View.
	///</summary>
	/// <remarks>
	/// IMPORTANT!!! You should not modify this partial  class, modify the Vw_CustomerList.cs file instead.
	/// All custom implementations should be done in the <see cref="Vw_CustomerList"/> class.
	/// </remarks>
	[DataObject]
	public partial class Vw_CustomerListServiceBase : ServiceViewBase<Vw_CustomerList>
	{

		#region Constructors
		///<summary>
		/// Creates a new <see cref="Vw_CustomerList"/> instance .
		///</summary>
		public Vw_CustomerListServiceBase() : base()
		{
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="Vw_CustomerList"/> instance.
		///</summary>
		///<param name="_id"></param>
		///<param name="_wholesalerId"></param>
		///<param name="_priCustomerNumber"></param>
		///<param name="_description"></param>
		///<param name="_externalCustomerNumber"></param>
		///<param name="_primaryContactName"></param>
		///<param name="_primaryContactPhoneNumber"></param>
		///<param name="_primaryContactEmailAddress"></param>
		///<param name="_primaryContactAddress1"></param>
		///<param name="_primaryContactAddress2"></param>
		///<param name="_primaryContactCity"></param>
		///<param name="_primaryContactCountry"></param>
		///<param name="_primaryContactRegion"></param>
		///<param name="_primaryContactPostalCode"></param>
		///<param name="_primaryContactFaxNumber"></param>
		///<param name="_billingContactName"></param>
		///<param name="_billingContactPhoneNumber"></param>
		///<param name="_billingContactEmailAddress"></param>
		///<param name="_billingContactAddress1"></param>
		///<param name="_billingContactAddress2"></param>
		///<param name="_billingContactCity"></param>
		///<param name="_billingContactCountry"></param>
		///<param name="_billingContactRegion"></param>
		///<param name="_billingContactPostalCode"></param>
		///<param name="_billingContactFaxNumber"></param>
		///<param name="_websiteUrl"></param>
		///<param name="_salesPersonId"></param>
		///<param name="_verticalId"></param>
		///<param name="_companyId"></param>
		///<param name="_currencyId"></param>
		///<param name="_billingPeriodCutoff"></param>
		///<param name="_taxableId"></param>
		///<param name="_creditCardNameOnCard"></param>
		///<param name="_creditCardNumber"></param>
		///<param name="_creditCardExp"></param>
		///<param name="_creditCardVerCode"></param>
		///<param name="_creditCardTypeName"></param>
		///<param name="_createdDate"></param>
		///<param name="_lastModified"></param>
		///<param name="_uniqueCustomerId"></param>
		///<param name="_enabled"></param>
		///<param name="_userId"></param>
		///<param name="_webGroupId"></param>
		///<param name="_companyName"></param>
		///<param name="_username"></param>
		///<param name="_password"></param>
		///<param name="_displayName"></param>
		///<param name="_email"></param>
		///<param name="_telephone"></param>
		///<param name="_userEnabled"></param>
		///<param name="_roleId"></param>
		///<param name="_mustChangePassword"></param>
		///<param name="_charityId"></param>
		///<param name="_webMemberId"></param>
		///<param name="_ddlDescription"></param>
		///<param name="_salesPerson"></param>
		///<param name="_salesManagerId"></param>
		///<param name="_verticalDescription"></param>
		public static Vw_CustomerList CreateVw_CustomerList(System.Int32 _id, System.String _wholesalerId, System.String _priCustomerNumber, System.String _description, System.String _externalCustomerNumber, System.String _primaryContactName, System.String _primaryContactPhoneNumber, System.String _primaryContactEmailAddress, System.String _primaryContactAddress1, System.String _primaryContactAddress2, System.String _primaryContactCity, System.String _primaryContactCountry, System.String _primaryContactRegion, System.String _primaryContactPostalCode, System.String _primaryContactFaxNumber, System.String _billingContactName, System.String _billingContactPhoneNumber, System.String _billingContactEmailAddress, System.String _billingContactAddress1, System.String _billingContactAddress2, System.String _billingContactCity, System.String _billingContactCountry, System.String _billingContactRegion, System.String _billingContactPostalCode, System.String _billingContactFaxNumber, System.String _websiteUrl, System.Int32 _salesPersonId, System.Int32 _verticalId, System.Int32 _companyId, System.String _currencyId, System.Int32 _billingPeriodCutoff, System.Int32 _taxableId, System.String _creditCardNameOnCard, System.String _creditCardNumber, System.String _creditCardExp, System.String _creditCardVerCode, System.String _creditCardTypeName, System.DateTime _createdDate, System.DateTime _lastModified, System.Guid _uniqueCustomerId, System.Boolean? _enabled, System.Int32? _userId, System.String _webGroupId, System.String _companyName, System.String _username, System.String _password, System.String _displayName, System.String _email, System.String _telephone, System.Boolean _userEnabled, System.Int32? _roleId, System.Boolean? _mustChangePassword, System.Int32? _charityId, System.String _webMemberId, System.String _ddlDescription, System.String _salesPerson, System.Int32? _salesManagerId, System.String _verticalDescription)
		{
			Vw_CustomerList newEntityVw_CustomerList = new Vw_CustomerList();
			newEntityVw_CustomerList.Id  = _id;
			newEntityVw_CustomerList.WholesalerId  = _wholesalerId;
			newEntityVw_CustomerList.PriCustomerNumber  = _priCustomerNumber;
			newEntityVw_CustomerList.Description  = _description;
			newEntityVw_CustomerList.ExternalCustomerNumber  = _externalCustomerNumber;
			newEntityVw_CustomerList.PrimaryContactName  = _primaryContactName;
			newEntityVw_CustomerList.PrimaryContactPhoneNumber  = _primaryContactPhoneNumber;
			newEntityVw_CustomerList.PrimaryContactEmailAddress  = _primaryContactEmailAddress;
			newEntityVw_CustomerList.PrimaryContactAddress1  = _primaryContactAddress1;
			newEntityVw_CustomerList.PrimaryContactAddress2  = _primaryContactAddress2;
			newEntityVw_CustomerList.PrimaryContactCity  = _primaryContactCity;
			newEntityVw_CustomerList.PrimaryContactCountry  = _primaryContactCountry;
			newEntityVw_CustomerList.PrimaryContactRegion  = _primaryContactRegion;
			newEntityVw_CustomerList.PrimaryContactPostalCode  = _primaryContactPostalCode;
			newEntityVw_CustomerList.PrimaryContactFaxNumber  = _primaryContactFaxNumber;
			newEntityVw_CustomerList.BillingContactName  = _billingContactName;
			newEntityVw_CustomerList.BillingContactPhoneNumber  = _billingContactPhoneNumber;
			newEntityVw_CustomerList.BillingContactEmailAddress  = _billingContactEmailAddress;
			newEntityVw_CustomerList.BillingContactAddress1  = _billingContactAddress1;
			newEntityVw_CustomerList.BillingContactAddress2  = _billingContactAddress2;
			newEntityVw_CustomerList.BillingContactCity  = _billingContactCity;
			newEntityVw_CustomerList.BillingContactCountry  = _billingContactCountry;
			newEntityVw_CustomerList.BillingContactRegion  = _billingContactRegion;
			newEntityVw_CustomerList.BillingContactPostalCode  = _billingContactPostalCode;
			newEntityVw_CustomerList.BillingContactFaxNumber  = _billingContactFaxNumber;
			newEntityVw_CustomerList.WebsiteUrl  = _websiteUrl;
			newEntityVw_CustomerList.SalesPersonId  = _salesPersonId;
			newEntityVw_CustomerList.VerticalId  = _verticalId;
			newEntityVw_CustomerList.CompanyId  = _companyId;
			newEntityVw_CustomerList.CurrencyId  = _currencyId;
			newEntityVw_CustomerList.BillingPeriodCutoff  = _billingPeriodCutoff;
			newEntityVw_CustomerList.TaxableId  = _taxableId;
			newEntityVw_CustomerList.CreditCardNameOnCard  = _creditCardNameOnCard;
			newEntityVw_CustomerList.CreditCardNumber  = _creditCardNumber;
			newEntityVw_CustomerList.CreditCardExp  = _creditCardExp;
			newEntityVw_CustomerList.CreditCardVerCode  = _creditCardVerCode;
			newEntityVw_CustomerList.CreditCardTypeName  = _creditCardTypeName;
			newEntityVw_CustomerList.CreatedDate  = _createdDate;
			newEntityVw_CustomerList.LastModified  = _lastModified;
			newEntityVw_CustomerList.UniqueCustomerId  = _uniqueCustomerId;
			newEntityVw_CustomerList.Enabled  = _enabled;
			newEntityVw_CustomerList.UserId  = _userId;
			newEntityVw_CustomerList.WebGroupId  = _webGroupId;
			newEntityVw_CustomerList.CompanyName  = _companyName;
			newEntityVw_CustomerList.Username  = _username;
			newEntityVw_CustomerList.Password  = _password;
			newEntityVw_CustomerList.DisplayName  = _displayName;
			newEntityVw_CustomerList.Email  = _email;
			newEntityVw_CustomerList.Telephone  = _telephone;
			newEntityVw_CustomerList.UserEnabled  = _userEnabled;
			newEntityVw_CustomerList.RoleId  = _roleId;
			newEntityVw_CustomerList.MustChangePassword  = _mustChangePassword;
			newEntityVw_CustomerList.CharityId  = _charityId;
			newEntityVw_CustomerList.WebMemberId  = _webMemberId;
			newEntityVw_CustomerList.DdlDescription  = _ddlDescription;
			newEntityVw_CustomerList.SalesPerson  = _salesPerson;
			newEntityVw_CustomerList.SalesManagerId  = _salesManagerId;
			newEntityVw_CustomerList.VerticalDescription  = _verticalDescription;
			return newEntityVw_CustomerList;
		}
		#endregion Constructors

		#region Fields
		//private static SecurityContext<Vw_CustomerList> securityContext = new SecurityContext<Vw_CustomerList>();
		private static readonly string layerExceptionPolicy = "NoneExceptionPolicy";
		private static readonly bool noTranByDefault = false;
		private static readonly int defaultMaxRecords = 10000;
		#endregion 
		
		#region Data Access Methods
			
		#region Get 
		/// <summary>
		/// Attempts to do a parameterized version of a simple whereclause. 
		/// Returns rows meeting the whereClause condition from the DataSource.
		/// </summary>
		/// <param name="whereClause">Specifies the condition for the rows returned by a query (Name='John Doe', Name='John Doe' AND Id='1', Name='John Doe' OR Id='1').</param>
        /// <param name="orderBy">Specifies the sort criteria for the rows in the DataSource (Name ASC; BirthDay DESC, Name ASC);</param>
		/// <remarks>Does NOT Support Advanced Operations such as SubSelects.  See GetPaged for that functionality.</remarks>
		/// <returns>Returns a typed collection of Entity objects.</returns>
		public override VList<Vw_CustomerList> Get(string whereClause, string orderBy)
		{
			int totalCount = -1;
			return Get(whereClause, orderBy, 0, defaultMaxRecords, out totalCount);
		}

		/// <summary>
		/// Returns rows meeting the whereClause condition from the DataSource.
		/// </summary>
		/// <param name="whereClause">Specifies the condition for the rows returned by a query (Name='John Doe', Name='John Doe' AND Id='1', Name='John Doe' OR Id='1').</param>
        /// <param name="orderBy">Specifies the sort criteria for the rows in the DataSource (Name ASC; BirthDay DESC, Name ASC);</param>
		/// <param name="start">Row number at which to start reading.</param>
		/// <param name="pageLength">Number of rows to return.</param>
		/// <param name="totalCount">out parameter to get total records for query</param>
		/// <remarks>Does NOT Support Advanced Operations such as SubSelects.  See GetPaged for that functionality.</remarks>
		/// <returns>Returns a typed collection TList{Vw_CustomerList} of <c>Vw_CustomerList</c> objects.</returns>
		public override VList<Vw_CustomerList> Get(string whereClause, string orderBy, int start, int pageLength, out int totalCount)
		{
			// throws security exception if not authorized
			//SecurityContext.IsAuthorized("Get");
								
			// get this data
			VList<Vw_CustomerList> list = null;
			totalCount = -1;
			TransactionManager transactionManager = null; 

			try
            {	
				//since this is a read operation, don't create a tran by default, only use tran if provided to us for custom isolation level
				transactionManager = ConnectionScope.ValidateOrCreateTransaction(noTranByDefault);
				NetTiersProvider dataProvider = ConnectionScope.Current.DataProvider;
					
				//Access repository
				list = dataProvider.Vw_CustomerListProvider.Get(transactionManager, whereClause, orderBy, start, pageLength, out totalCount);
				
				//if borrowed tran, leave open for next call
			}
            catch (Exception exc)
            {
				//if open, rollback, it's possible this is part of a larger commit
                if (transactionManager != null && transactionManager.IsOpen) 
					transactionManager.Rollback();
				
				//Handle exception based on policy
                if (DomainUtil.HandleException(exc, layerExceptionPolicy)) 
					throw;
			}
			return list;
		}
		
		#endregion Get Methods
		
		#region GetAll
		/// <summary>
		/// Get a complete collection of <see cref="Vw_CustomerList" /> entities.
		/// </summary>
		/// <returns></returns>
		public virtual VList<Vw_CustomerList> GetAll() 
		{
			int totalCount = -1;
			return GetAll(0, defaultMaxRecords, out totalCount);
		}

       
		/// <summary>
		/// Get a set portion of a complete list of <see cref="Vw_CustomerList" /> entities
		/// </summary>
		/// <param name="start">Row number at which to start reading.</param>
		/// <param name="pageLength">Number of rows to return.</param>
		/// <param name="totalCount">out parameter, number of total rows in given query.</param>
		/// <returns>a <see cref="TList{Vw_CustomerList}"/> </returns>
		public override VList<Vw_CustomerList> GetAll(int start, int pageLength, out int totalCount) 
		{
			// throws security exception if not authorized
			//SecurityContext.IsAuthorized("GetAll");
			
			// get this data
			VList<Vw_CustomerList> list = null;
			totalCount = -1;
			TransactionManager transactionManager = null; 

			try
            {	
				//since this is a read operation, don't create a tran by default, only use tran if provided to us for custom isolation level
				transactionManager = ConnectionScope.ValidateOrCreateTransaction(noTranByDefault);
				NetTiersProvider dataProvider = ConnectionScope.Current.DataProvider;					

				//Access repository
				list = dataProvider.Vw_CustomerListProvider.GetAll(transactionManager, start, pageLength, out totalCount);	
			}
            catch (Exception exc)
            {
				//if open, rollback, it's possible this is part of a larger commit
                if (transactionManager != null && transactionManager.IsOpen) 
					transactionManager.Rollback();
				
				//Handle exception based on policy
                if (DomainUtil.HandleException(exc, layerExceptionPolicy)) 
					throw;
			}
			return list;
		}
		#endregion GetAll

		#region GetPaged
		/// <summary>
		/// Gets a page of <see cref="TList{Vw_CustomerList}" /> rows from the DataSource.
		/// </summary>
		/// <param name="totalCount">Out Parameter, Number of rows in the DataSource.</param>
		/// <remarks></remarks>
		/// <returns>Returns a typed collection of <c>Vw_CustomerList</c> objects.</returns>
		public virtual VList<Vw_CustomerList> GetPaged(out int totalCount)
		{
			return GetPaged(null, null, 0, defaultMaxRecords, out totalCount);
		}
		
		/// <summary>
		/// Gets a page of <see cref="TList{Vw_CustomerList}" /> rows from the DataSource.
		/// </summary>
		/// <param name="start">Row number at which to start reading.</param>
		/// <param name="pageLength">Number of rows to return.</param>
		/// <param name="totalCount">Number of rows in the DataSource.</param>
		/// <remarks></remarks>
		/// <returns>Returns a typed collection of <c>Vw_CustomerList</c> objects.</returns>
		public virtual VList<Vw_CustomerList> GetPaged(int start, int pageLength, out int totalCount)
		{
			return GetPaged(null, null, start, pageLength, out totalCount);
		}

		/// <summary>
		/// Gets a page of entity rows with a <see cref="TList{Vw_CustomerList}" /> from the DataSource with a where clause and order by clause.
		/// </summary>
		/// <param name="whereClause">Specifies the condition for the rows returned by a query (Name='John Doe', Name='John Doe' AND Id='1', Name='John Doe' OR Id='1').</param>
		/// <param name="orderBy">Specifies the sort criteria for the rows in the DataSource (Name ASC; BirthDay DESC, Name ASC).</param>
		/// <param name="start">Row number at which to start reading.</param>
		/// <param name="pageLength">Number of rows to return.</param>
		/// <param name="totalCount">Out Parameter, Number of rows in the DataSource.</param>
		/// <remarks></remarks>
		/// <returns>Returns a typed collection of <c>Vw_CustomerList</c> objects.</returns>
		public override VList<Vw_CustomerList> GetPaged(string whereClause,string orderBy, int start, int pageLength, out int totalCount)
		{
			// throws security exception if not authorized
			//SecurityContext.IsAuthorized("GetPaged");
			
			// get this data
			VList<Vw_CustomerList> list = null;
			totalCount = -1;
			TransactionManager transactionManager = null; 

			try
            {	
				//since this is a read operation, don't create a tran by default, only use tran if provided to us for custom isolation level
				transactionManager = ConnectionScope.ValidateOrCreateTransaction(noTranByDefault);
				NetTiersProvider dataProvider = ConnectionScope.Current.DataProvider;
					
				//Access repository
				list = dataProvider.Vw_CustomerListProvider.GetPaged(transactionManager, whereClause, orderBy, start, pageLength, out totalCount);
				
				//if borrowed tran, leave open for next call
			}
            catch (Exception exc)
            {
				//if open, rollback, it's possible this is part of a larger commit
                if (transactionManager != null && transactionManager.IsOpen) 
					transactionManager.Rollback();
				
				//Handle exception based on policy
                if (DomainUtil.HandleException(exc, layerExceptionPolicy)) 
					throw;
			}
			return list;			
		}
		
		/// <summary>
		/// Gets the number of rows in the DataSource that match the specified whereClause.
		/// This method is only provided as a workaround for the ObjectDataSource's need to 
		/// execute another method to discover the total count instead of using another param, like our out param.  
		/// This method should be avoided if using the ObjectDataSource or another method.
		/// </summary>
		/// <param name="whereClause">Specifies the condition for the rows returned by a query (Name='John Doe', Name='John Doe' AND Id='1', Name='John Doe' OR Id='1').</param>
		/// <param name="totalCount">Number of rows in the DataSource.</param>
		/// <returns>Returns the number of rows.</returns>
		public int GetTotalItems(string whereClause, out int totalCount)
		{
			GetPaged(whereClause, null, 0, defaultMaxRecords, out totalCount);
			return totalCount;
		}
		#endregion GetPaged	

		#region Find Methods

		/// <summary>
		/// 	Returns rows from the DataSource that meet the parameter conditions.
		/// </summary>
		/// <param name="parameters">A collection of <see cref="SqlFilterParameter"/> objects.</param>
		/// <returns>Returns a typed collection of <c>Vw_CustomerList</c> objects.</returns>
		public virtual VList<Vw_CustomerList> Find(IFilterParameterCollection parameters)
		{
			return Find(parameters, null);
		}
		
		/// <summary>
		/// 	Returns rows from the DataSource that meet the parameter conditions.
		/// </summary>
		/// <param name="parameters">A collection of <see cref="SqlFilterParameter"/> objects.</param>
		/// <param name="orderBy">Specifies the sort criteria for the rows in the DataSource (Name ASC; BirthDay DESC, Name ASC);</param>
		/// <returns>Returns a typed collection of <c>Vw_CustomerList</c> objects.</returns>
		public virtual VList<Vw_CustomerList> Find(IFilterParameterCollection parameters, string orderBy)
		{
			int count = 0;
			return Find(parameters, orderBy, 0, defaultMaxRecords, out count);
		}
		
		/// <summary>
		/// 	Returns rows from the DataSource that meet the parameter conditions.
		/// </summary>
		/// <param name="parameters">A collection of <see cref="SqlFilterParameter"/> objects.</param>
		/// <param name="orderBy">Specifies the sort criteria for the rows in the DataSource (Name ASC; BirthDay DESC, Name ASC);</param>
		/// <param name="start">Row number at which to start reading.</param>
		/// <param name="pageLength">Number of rows to return.</param>
		/// <param name="count">out. The number of rows that match this query.</param>
		/// <returns>Returns a typed collection of <c>Vw_CustomerList</c> objects.</returns>
		public override VList<Vw_CustomerList> Find(IFilterParameterCollection parameters, string orderBy, int start, int pageLength, out int count)
		{
			// throws security exception if not authorized
			//SecurityContext.IsAuthorized("Find");
								
			// get this data
			TransactionManager transactionManager = null; 
			VList<Vw_CustomerList> list = null;
			count = -1;
			
			try
            {	
				//since this is a read operation, don't create a tran by default, only use tran if provided to us for custom isolation level
				transactionManager = ConnectionScope.ValidateOrCreateTransaction(noTranByDefault);
				NetTiersProvider dataProvider = ConnectionScope.Current.DataProvider;
					
				//Access repository
				list = dataProvider.Vw_CustomerListProvider.Find(transactionManager, parameters, orderBy, start, pageLength, out count);
			}
            catch (Exception exc)
            {
				//if open, rollback, it's possible this is part of a larger commit
                if (transactionManager != null && transactionManager.IsOpen) 
					transactionManager.Rollback();
				
				//Handle exception based on policy
                if (DomainUtil.HandleException(exc, layerExceptionPolicy)) 
					throw;
			}
			
			return list;
		}
		
		#endregion Find Methods
		
		#region Custom Methods
		#endregion
		
		#endregion Data Access Methods
		
	
	}//End Class
} // end namespace



