
/*
	File generated by NetTiers templates [www.nettiers.com]
	Important: Do not modify this file. Edit the file CompanyLeadTrackingNotes.cs instead.
*/

#region using directives

using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;

#endregion

namespace CONFDB.Entities
{
	///<summary>
	/// An object representation of the 'CompanyLeadTrackingNotes' table. [No description found the database]	
	///</summary>
	[Serializable, DataObject]
	[CLSCompliant(true)]
	public abstract partial class CompanyLeadTrackingNotesBase : EntityBase, CONFDB.Entities.ICompanyLeadTrackingNotes, IEntityId<CompanyLeadTrackingNotesKey>, System.IComparable, System.ICloneable, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private CompanyLeadTrackingNotesEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private CompanyLeadTrackingNotesEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private CompanyLeadTrackingNotesEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<CompanyLeadTrackingNotes> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>	
		[field:NonSerialized]
		public event CompanyLeadTrackingNotesEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event CompanyLeadTrackingNotesEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="CompanyLeadTrackingNotesBase"/> instance.
		///</summary>
		public CompanyLeadTrackingNotesBase()
		{
			this.entityData = new CompanyLeadTrackingNotesEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="CompanyLeadTrackingNotesBase"/> instance.
		///</summary>
		///<param name="_id"></param>
		///<param name="_companyLeadTrackingId"></param>
		///<param name="_notes"></param>
		///<param name="_oldValues"></param>
		///<param name="_createdDate"></param>
		///<param name="_modifiedBy"></param>
		public CompanyLeadTrackingNotesBase(System.Int32 _id, System.Int32 _companyLeadTrackingId, 
			System.String _notes, System.String _oldValues, System.DateTime _createdDate, 
			System.String _modifiedBy)
		{
			this.entityData = new CompanyLeadTrackingNotesEntityData();
			this.backupData = null;

			this.Id = _id;
			this.CompanyLeadTrackingId = _companyLeadTrackingId;
			this.Notes = _notes;
			this.OldValues = _oldValues;
			this.CreatedDate = _createdDate;
			this.ModifiedBy = _modifiedBy;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="CompanyLeadTrackingNotes"/> instance.
		///</summary>
		///<param name="_id"></param>
		///<param name="_companyLeadTrackingId"></param>
		///<param name="_notes"></param>
		///<param name="_oldValues"></param>
		///<param name="_createdDate"></param>
		///<param name="_modifiedBy"></param>
		public static CompanyLeadTrackingNotes CreateCompanyLeadTrackingNotes(System.Int32 _id, System.Int32 _companyLeadTrackingId, 
			System.String _notes, System.String _oldValues, System.DateTime _createdDate, 
			System.String _modifiedBy)
		{
			CompanyLeadTrackingNotes newCompanyLeadTrackingNotes = new CompanyLeadTrackingNotes();
			newCompanyLeadTrackingNotes.Id = _id;
			newCompanyLeadTrackingNotes.CompanyLeadTrackingId = _companyLeadTrackingId;
			newCompanyLeadTrackingNotes.Notes = _notes;
			newCompanyLeadTrackingNotes.OldValues = _oldValues;
			newCompanyLeadTrackingNotes.CreatedDate = _createdDate;
			newCompanyLeadTrackingNotes.ModifiedBy = _modifiedBy;
			return newCompanyLeadTrackingNotes;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the Id property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, false, false)]
		public virtual System.Int32 Id
		{
			get
			{
				return this.entityData.Id; 
			}
			
			set
			{
				if (this.entityData.Id == value)
					return;
					
				OnColumnChanging(CompanyLeadTrackingNotesColumn.Id, this.entityData.Id);
				this.entityData.Id = value;
				this.EntityId.Id = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(CompanyLeadTrackingNotesColumn.Id, this.entityData.Id);
				OnPropertyChanged("Id");
			}
		}
		
		/// <summary>
		/// 	Get the original value of the ID property.
		///		
		/// </summary>
		/// <remarks>This is the original value of the ID property.</remarks>
		/// <value>This type is int</value>
		[BrowsableAttribute(false)/*, XmlIgnoreAttribute()*/]
		public  virtual System.Int32 OriginalId
		{
			get { return this.entityData.OriginalId; }
			set { this.entityData.OriginalId = value; }
		}
		
		/// <summary>
		/// 	Gets or sets the CompanyLeadTrackingId property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.Int32 CompanyLeadTrackingId
		{
			get
			{
				return this.entityData.CompanyLeadTrackingId; 
			}
			
			set
			{
				if (this.entityData.CompanyLeadTrackingId == value)
					return;
					
				OnColumnChanging(CompanyLeadTrackingNotesColumn.CompanyLeadTrackingId, this.entityData.CompanyLeadTrackingId);
				this.entityData.CompanyLeadTrackingId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(CompanyLeadTrackingNotesColumn.CompanyLeadTrackingId, this.entityData.CompanyLeadTrackingId);
				OnPropertyChanged("CompanyLeadTrackingId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Notes property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 1000)]
		public virtual System.String Notes
		{
			get
			{
				return this.entityData.Notes; 
			}
			
			set
			{
				if (this.entityData.Notes == value)
					return;
					
				OnColumnChanging(CompanyLeadTrackingNotesColumn.Notes, this.entityData.Notes);
				this.entityData.Notes = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(CompanyLeadTrackingNotesColumn.Notes, this.entityData.Notes);
				OnPropertyChanged("Notes");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the OldValues property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 1000)]
		public virtual System.String OldValues
		{
			get
			{
				return this.entityData.OldValues; 
			}
			
			set
			{
				if (this.entityData.OldValues == value)
					return;
					
				OnColumnChanging(CompanyLeadTrackingNotesColumn.OldValues, this.entityData.OldValues);
				this.entityData.OldValues = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(CompanyLeadTrackingNotesColumn.OldValues, this.entityData.OldValues);
				OnPropertyChanged("OldValues");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the CreatedDate property. 
		///		
		/// </summary>
		/// <value>This type is datetime.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.DateTime CreatedDate
		{
			get
			{
				return this.entityData.CreatedDate; 
			}
			
			set
			{
				if (this.entityData.CreatedDate == value)
					return;
					
				OnColumnChanging(CompanyLeadTrackingNotesColumn.CreatedDate, this.entityData.CreatedDate);
				this.entityData.CreatedDate = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(CompanyLeadTrackingNotesColumn.CreatedDate, this.entityData.CreatedDate);
				OnPropertyChanged("CreatedDate");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the ModifiedBy property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 50)]
		public virtual System.String ModifiedBy
		{
			get
			{
				return this.entityData.ModifiedBy; 
			}
			
			set
			{
				if (this.entityData.ModifiedBy == value)
					return;
					
				OnColumnChanging(CompanyLeadTrackingNotesColumn.ModifiedBy, this.entityData.ModifiedBy);
				this.entityData.ModifiedBy = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(CompanyLeadTrackingNotesColumn.ModifiedBy, this.entityData.ModifiedBy);
				OnPropertyChanged("ModifiedBy");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		/// <summary>
		/// Gets or sets the source <see cref="CompanyLeadTracking"/>.
		/// </summary>
		/// <value>The source CompanyLeadTracking for CompanyLeadTrackingId.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual CompanyLeadTracking CompanyLeadTrackingIdSource
      	{
            get { return entityData.CompanyLeadTrackingIdSource; }
            set { entityData.CompanyLeadTrackingIdSource = value; }
      	}
		#endregion
		
		#region Children Collections
		#endregion Children Collections
		
		#endregion
		
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
			ValidationRules.AddRule(
				Validation.CommonRules.StringMaxLength, 
				new Validation.CommonRules.MaxLengthRuleArgs("Notes", "Notes", 1000));
			ValidationRules.AddRule(
				Validation.CommonRules.StringMaxLength, 
				new Validation.CommonRules.MaxLengthRuleArgs("OldValues", "Old Values", 1000));
			ValidationRules.AddRule(
				Validation.CommonRules.StringMaxLength, 
				new Validation.CommonRules.MaxLengthRuleArgs("ModifiedBy", "Modified By", 50));
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "CompanyLeadTrackingNotes"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"ID", "CompanyLeadTrackingID", "Notes", "OldValues", "CreatedDate", "ModifiedBy"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as CompanyLeadTrackingNotesEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (CompanyLeadTrackingNotes) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<CompanyLeadTrackingNotes>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as CompanyLeadTrackingNotes);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed CompanyLeadTrackingNotes Entity 
		///</summary>
		public virtual CompanyLeadTrackingNotes Copy()
		{
			//shallow copy entity
			CompanyLeadTrackingNotes copy = new CompanyLeadTrackingNotes();
			copy.SuppressEntityEvents = true;
			copy.Id = this.Id;
			copy.OriginalId = this.OriginalId;
			copy.CompanyLeadTrackingId = this.CompanyLeadTrackingId;
			copy.Notes = this.Notes;
			copy.OldValues = this.OldValues;
			copy.CreatedDate = this.CreatedDate;
			copy.ModifiedBy = this.ModifiedBy;
			
			copy.CompanyLeadTrackingIdSource = MakeCopyOf(this.CompanyLeadTrackingIdSource) as CompanyLeadTracking;
		
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy();
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		///  Returns a Typed CompanyLeadTrackingNotes Entity which is a deep copy of the current entity.
		///</summary>
		public virtual CompanyLeadTrackingNotes DeepCopy()
		{
			return EntityHelper.Clone<CompanyLeadTrackingNotes>(this as CompanyLeadTrackingNotes);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as CompanyLeadTrackingNotesEntityData;
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as CompanyLeadTrackingNotesEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(CompanyLeadTrackingNotesColumn column)
		{
			switch(column)
			{
					case CompanyLeadTrackingNotesColumn.Id:
					return entityData.Id != _originalData.Id;
					case CompanyLeadTrackingNotesColumn.CompanyLeadTrackingId:
					return entityData.CompanyLeadTrackingId != _originalData.CompanyLeadTrackingId;
					case CompanyLeadTrackingNotesColumn.Notes:
					return entityData.Notes != _originalData.Notes;
					case CompanyLeadTrackingNotesColumn.OldValues:
					return entityData.OldValues != _originalData.OldValues;
					case CompanyLeadTrackingNotesColumn.CreatedDate:
					return entityData.CreatedDate != _originalData.CreatedDate;
					case CompanyLeadTrackingNotesColumn.ModifiedBy:
					return entityData.ModifiedBy != _originalData.ModifiedBy;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if [has data changed]; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.Id != _originalData.Id;
			result = result || entityData.CompanyLeadTrackingId != _originalData.CompanyLeadTrackingId;
			result = result || entityData.Notes != _originalData.Notes;
			result = result || entityData.OldValues != _originalData.OldValues;
			result = result || entityData.CreatedDate != _originalData.CreatedDate;
			result = result || entityData.ModifiedBy != _originalData.ModifiedBy;
			return result;
}	
		
		#endregion

        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="CompanyLeadTrackingNotesBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			if (Object1 is CompanyLeadTrackingNotesBase)
				return Equals(this, (CompanyLeadTrackingNotesBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="CompanyLeadTrackingNotesBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.Id.GetHashCode() ^ 
					this.CompanyLeadTrackingId.GetHashCode() ^ 
					((this.Notes == null) ? string.Empty : this.Notes.ToString()).GetHashCode() ^ 
					((this.OldValues == null) ? string.Empty : this.OldValues.ToString()).GetHashCode() ^ 
					this.CreatedDate.GetHashCode() ^ 
					((this.ModifiedBy == null) ? string.Empty : this.ModifiedBy.ToString()).GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="CompanyLeadTrackingNotesBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(CompanyLeadTrackingNotesBase toObject)
		{
			if (toObject == null)
				return false;
			return Equals(this, toObject);
		}
		
		
		///<summary>
		/// Determines whether the specified <see cref="CompanyLeadTrackingNotesBase"/> instances are considered equal.
		///</summary>
		///<param name="Object1">The first <see cref="CompanyLeadTrackingNotesBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="CompanyLeadTrackingNotesBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool Equals(CompanyLeadTrackingNotesBase Object1, CompanyLeadTrackingNotesBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.Id != Object2.Id)
				equal = false;
			if (Object1.CompanyLeadTrackingId != Object2.CompanyLeadTrackingId)
				equal = false;
			if ( Object1.Notes != null && Object2.Notes != null )
			{
				if (Object1.Notes != Object2.Notes)
					equal = false;
			}
			else if (Object1.Notes == null ^ Object2.Notes == null )
			{
				equal = false;
			}
			if ( Object1.OldValues != null && Object2.OldValues != null )
			{
				if (Object1.OldValues != Object2.OldValues)
					equal = false;
			}
			else if (Object1.OldValues == null ^ Object2.OldValues == null )
			{
				equal = false;
			}
			if (Object1.CreatedDate != Object2.CreatedDate)
				equal = false;
			if ( Object1.ModifiedBy != null && Object2.ModifiedBy != null )
			{
				if (Object1.ModifiedBy != Object2.ModifiedBy)
					equal = false;
			}
			else if (Object1.ModifiedBy == null ^ Object2.ModifiedBy == null )
			{
				equal = false;
			}
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((CompanyLeadTrackingNotesBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static CompanyLeadTrackingNotesComparer GetComparer()
        {
            return new CompanyLeadTrackingNotesComparer();
        }
        */

        // Comparer delegates back to CompanyLeadTrackingNotes
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(CompanyLeadTrackingNotes rhs, CompanyLeadTrackingNotesColumn which)
        {
            switch (which)
            {
            	
            	
            	case CompanyLeadTrackingNotesColumn.Id:
            		return this.Id.CompareTo(rhs.Id);
            		
            		                 
            	
            	
            	case CompanyLeadTrackingNotesColumn.CompanyLeadTrackingId:
            		return this.CompanyLeadTrackingId.CompareTo(rhs.CompanyLeadTrackingId);
            		
            		                 
            	
            	
            	case CompanyLeadTrackingNotesColumn.Notes:
            		return this.Notes.CompareTo(rhs.Notes);
            		
            		                 
            	
            	
            	case CompanyLeadTrackingNotesColumn.OldValues:
            		return this.OldValues.CompareTo(rhs.OldValues);
            		
            		                 
            	
            	
            	case CompanyLeadTrackingNotesColumn.CreatedDate:
            		return this.CreatedDate.CompareTo(rhs.CreatedDate);
            		
            		                 
            	
            	
            	case CompanyLeadTrackingNotesColumn.ModifiedBy:
            		return this.ModifiedBy.CompareTo(rhs.ModifiedBy);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<CompanyLeadTrackingNotesKey> Members
		
		// member variable for the EntityId property
		private CompanyLeadTrackingNotesKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual CompanyLeadTrackingNotesKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new CompanyLeadTrackingNotesKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("CompanyLeadTrackingNotes")
					.Append("|").Append( this.Id.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{7}{6}- Id: {0}{6}- CompanyLeadTrackingId: {1}{6}- Notes: {2}{6}- OldValues: {3}{6}- CreatedDate: {4}{6}- ModifiedBy: {5}{6}", 
				this.Id,
				this.CompanyLeadTrackingId,
				(this.Notes == null) ? string.Empty : this.Notes.ToString(),
				(this.OldValues == null) ? string.Empty : this.OldValues.ToString(),
				this.CreatedDate,
				(this.ModifiedBy == null) ? string.Empty : this.ModifiedBy.ToString(),
				System.Environment.NewLine, 
				this.GetType());
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'CompanyLeadTrackingNotes' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class CompanyLeadTrackingNotesEntityData : ICloneable
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
			/// <summary>			
			/// ID : 
			/// </summary>
			/// <remarks>Member of the primary key of the underlying table "CompanyLeadTrackingNotes"</remarks>
			public System.Int32 Id;
				
			/// <summary>
			/// keep a copy of the original so it can be used for editable primary keys.
			/// </summary>
			public System.Int32 OriginalId;
			
		#endregion
		
		#region Non Primary key(s)
		
		
		/// <summary>
		/// CompanyLeadTrackingID : 
		/// </summary>
		public System.Int32		  CompanyLeadTrackingId = (int)0;
		
		/// <summary>
		/// Notes : 
		/// </summary>
		public System.String		  Notes = null;
		
		/// <summary>
		/// OldValues : 
		/// </summary>
		public System.String		  OldValues = null;
		
		/// <summary>
		/// CreatedDate : 
		/// </summary>
		public System.DateTime		  CreatedDate = DateTime.MinValue;
		
		/// <summary>
		/// ModifiedBy : 
		/// </summary>
		public System.String		  ModifiedBy = null;
		#endregion
			
		#region Source Foreign Key Property
				
		private CompanyLeadTracking _companyLeadTrackingIdSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="CompanyLeadTracking"/>.
		/// </summary>
		/// <value>The source CompanyLeadTracking for CompanyLeadTrackingId.</value>
        [XmlIgnore()]
		[Browsable(false)]
		public virtual CompanyLeadTracking CompanyLeadTrackingIdSource
      	{
            get { return this._companyLeadTrackingIdSource; }
            set { this._companyLeadTrackingIdSource = value; }
      	}
		#endregion
		#endregion Variable Declarations
	
		#region Data Properties

		#endregion Data Properties
		
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			CompanyLeadTrackingNotesEntityData _tmp = new CompanyLeadTrackingNotesEntityData();
						
			_tmp.Id = this.Id;
			_tmp.OriginalId = this.OriginalId;
			
			_tmp.CompanyLeadTrackingId = this.CompanyLeadTrackingId;
			_tmp.Notes = this.Notes;
			_tmp.OldValues = this.OldValues;
			_tmp.CreatedDate = this.CreatedDate;
			_tmp.ModifiedBy = this.ModifiedBy;
			
			#region Source Parent Composite Entities
			if (this.CompanyLeadTrackingIdSource != null)
				_tmp.CompanyLeadTrackingIdSource = MakeCopyOf(this.CompanyLeadTrackingIdSource) as CompanyLeadTracking;
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct



		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="CompanyLeadTrackingNotesColumn"/> which has raised the event.</param>
		public void OnColumnChanging(CompanyLeadTrackingNotesColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="CompanyLeadTrackingNotesColumn"/> which has raised the event.</param>
		public void OnColumnChanged(CompanyLeadTrackingNotesColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="CompanyLeadTrackingNotesColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public void OnColumnChanging(CompanyLeadTrackingNotesColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
				EntityManager.StopTracking(entityTrackingKey);
				
			if (!SuppressEntityEvents)
			{
				CompanyLeadTrackingNotesEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new CompanyLeadTrackingNotesEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="CompanyLeadTrackingNotesColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public void OnColumnChanged(CompanyLeadTrackingNotesColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				CompanyLeadTrackingNotesEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new CompanyLeadTrackingNotesEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region CompanyLeadTrackingNotesEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="CompanyLeadTrackingNotes"/> object.
	/// </remarks>
	public class CompanyLeadTrackingNotesEventArgs : System.EventArgs
	{
		private CompanyLeadTrackingNotesColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the CompanyLeadTrackingNotesEventArgs class.
		///</summary>
		public CompanyLeadTrackingNotesEventArgs(CompanyLeadTrackingNotesColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the CompanyLeadTrackingNotesEventArgs class.
		///</summary>
		public CompanyLeadTrackingNotesEventArgs(CompanyLeadTrackingNotesColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The CompanyLeadTrackingNotesColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="CompanyLeadTrackingNotesColumn" />
		public CompanyLeadTrackingNotesColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all CompanyLeadTrackingNotes related events.
	///</summary>
	public delegate void CompanyLeadTrackingNotesEventHandler(object sender, CompanyLeadTrackingNotesEventArgs e);
	
	#region CompanyLeadTrackingNotesComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class CompanyLeadTrackingNotesComparer : System.Collections.Generic.IComparer<CompanyLeadTrackingNotes>
	{
		CompanyLeadTrackingNotesColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:CompanyLeadTrackingNotesComparer"/> class.
        /// </summary>
		public CompanyLeadTrackingNotesComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:CompanyLeadTrackingNotesComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public CompanyLeadTrackingNotesComparer(CompanyLeadTrackingNotesColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <c cref="CompanyLeadTrackingNotes"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <c cref="CompanyLeadTrackingNotes"/> to compare.</param>
        /// <param name="b">The second <c>CompanyLeadTrackingNotes</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(CompanyLeadTrackingNotes a, CompanyLeadTrackingNotes b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(CompanyLeadTrackingNotes entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(CompanyLeadTrackingNotes a, CompanyLeadTrackingNotes b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public CompanyLeadTrackingNotesColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region CompanyLeadTrackingNotesKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="CompanyLeadTrackingNotes"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class CompanyLeadTrackingNotesKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the CompanyLeadTrackingNotesKey class.
		/// </summary>
		public CompanyLeadTrackingNotesKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the CompanyLeadTrackingNotesKey class.
		/// </summary>
		public CompanyLeadTrackingNotesKey(CompanyLeadTrackingNotesBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.Id = entity.Id;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the CompanyLeadTrackingNotesKey class.
		/// </summary>
		public CompanyLeadTrackingNotesKey(System.Int32 _id)
		{
			#region Init Properties

			this.Id = _id;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private CompanyLeadTrackingNotesBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public CompanyLeadTrackingNotesBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the Id property
		private System.Int32 _id;
		
		/// <summary>
		/// Gets or sets the Id property.
		/// </summary>
		public System.Int32 Id
		{
			get { return _id; }
			set
			{
				if ( this.Entity != null )
					this.Entity.Id = value;
				
				_id = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				Id = ( values["Id"] != null ) ? (System.Int32) EntityUtil.ChangeType(values["Id"], typeof(System.Int32)) : (int)0;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("Id", Id);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("Id: {0}{1}",
								Id,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region CompanyLeadTrackingNotesColumn Enum
	
	/// <summary>
	/// Enumerate the CompanyLeadTrackingNotes columns.
	/// </summary>
	[Serializable]
	public enum CompanyLeadTrackingNotesColumn : int
	{
		/// <summary>
		/// Id : 
		/// </summary>
		[EnumTextValue("ID")]
		[ColumnEnum("ID", typeof(System.Int32), System.Data.DbType.Int32, true, false, false)]
		Id = 1,
		/// <summary>
		/// CompanyLeadTrackingId : 
		/// </summary>
		[EnumTextValue("CompanyLeadTrackingID")]
		[ColumnEnum("CompanyLeadTrackingID", typeof(System.Int32), System.Data.DbType.Int32, false, false, false)]
		CompanyLeadTrackingId = 2,
		/// <summary>
		/// Notes : 
		/// </summary>
		[EnumTextValue("Notes")]
		[ColumnEnum("Notes", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 1000)]
		Notes = 3,
		/// <summary>
		/// OldValues : 
		/// </summary>
		[EnumTextValue("OldValues")]
		[ColumnEnum("OldValues", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 1000)]
		OldValues = 4,
		/// <summary>
		/// CreatedDate : 
		/// </summary>
		[EnumTextValue("CreatedDate")]
		[ColumnEnum("CreatedDate", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, false)]
		CreatedDate = 5,
		/// <summary>
		/// ModifiedBy : 
		/// </summary>
		[EnumTextValue("ModifiedBy")]
		[ColumnEnum("ModifiedBy", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 50)]
		ModifiedBy = 6
	}//End enum

	#endregion CompanyLeadTrackingNotesColumn Enum

} // end namespace
