using System;
using System.ComponentModel;

namespace CONFDB.Entities
{
	/// <summary>
	///		The data structure representation of the 'AccessType_ProductRate' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IAccessType_ProductRate 
	{
		/// <summary>			
		/// ID : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "AccessType_ProductRate"</remarks>
		System.Int32 Id { get; set; }
				
		
		
		/// <summary>
		/// AccessTypeID : 
		/// </summary>
		System.Int32  AccessTypeId  { get; set; }
		
		/// <summary>
		/// ProductRateID : 
		/// </summary>
		System.Int32  ProductRateId  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties

		#endregion Data Properties

	}
}


